CREATE TABLE [dbo].[Board]
(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Board PRIMARY KEY,
	ModelId INT NULL CONSTRAINT FK_Board_BoardModel FOREIGN KEY REFERENCES BoardModel(Id),
	Volume INT NOT NULL
)
